M = [[I6.*sin(\[Theta]2+\[Theta]3+\[Theta]4).^2.*sin(\[Theta]5).^2+m6.*(\
cos(\[Theta]5).*(l2.*cos(\[Theta]2)+l3.* ...
  cos(\[Theta]2+\[Theta]3)+(-1).*l5.*sin(\[Theta]2+\[Theta]3+\[Theta]\
4))+(-1).*l4.*cos(\[Theta]2+\[Theta]3+\[Theta]4).*sin( ...
  \[Theta]5)).^2+I6.*(cos(\[Theta]5).*cos(\[Theta]6).*sin(\[Theta]2+\
\[Theta]3+\[Theta]4)+cos(\[Theta]2+\[Theta]3+\[Theta]4).*sin( ...
  \[Theta]6)).^2+I6.*(cos(\[Theta]2+\[Theta]3+\[Theta]4).*cos(\[Theta]\
6)+(-1).*cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).* ...
  sin(\[Theta]6)).^2+m6.*(sin(\[Theta]2).*((-1).*cos(\[Theta]6).*((l6+\
l4.*cos(\[Theta]5)).*sin( ...
  \[Theta]3+\[Theta]4)+(l5.*cos(\[Theta]3+\[Theta]4)+l3.*sin(\[Theta]\
3)).*sin(\[Theta]5))+(-1).*cos(\[Theta]3+\[Theta]4).*( ...
  l4+l6.*cos(\[Theta]5)).*sin(\[Theta]6))+cos(\[Theta]2).*(cos(\
\[Theta]3+\[Theta]4).*(l6+l4.*cos(\[Theta]5)).* ...
  cos(\[Theta]6)+cos(\[Theta]6).*(l2+l3.*cos(\[Theta]3)+(-1).*l5.*sin(\
\[Theta]3+\[Theta]4)).*sin(\[Theta]5)+( ...
  -1).*(l4+l6.*cos(\[Theta]5)).*sin(\[Theta]3+\[Theta]4).*sin(\[Theta]\
6))).^2+m6.*((-1).*cos(\[Theta]3) ...
  .*(l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]2+\[Theta]4)+\
((l6+l4.*cos(\[Theta]5)).*sin(\[Theta]3) ...
  .*sin(\[Theta]2+\[Theta]4)+((-1).*cos(\[Theta]2).*(l2+l3.*cos(\
\[Theta]3))+l3.*sin(\[Theta]2).*sin(\[Theta]3) ...
  +l5.*cos(\[Theta]3).*sin(\[Theta]2+\[Theta]4)).*sin(\[Theta]5)).*\
sin(\[Theta]6)+(-1).*cos(\[Theta]2+\[Theta]4).*(( ...
  l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]3)+(cos(\[Theta]\
3).*(l6+l4.*cos(\[Theta]5))+(-1) ...
  .*l5.*sin(\[Theta]3).*sin(\[Theta]5)).*sin(\[Theta]6))).^2;(-1).*I6.\
*cos(\[Theta]5).*sin(\[Theta]2+ ...
  \[Theta]3+\[Theta]4).*sin(\[Theta]5)+m6.*((-1).*l5+l3.*sin(\[Theta]\
4)+l2.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]5) ...
  .*(cos(\[Theta]5).*(l2.*cos(\[Theta]2)+l3.*cos(\[Theta]2+\[Theta]3)+\
(-1).*l5.*sin(\[Theta]2+\[Theta]3+\[Theta]4))+( ...
  -1).*l4.*cos(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]5))+I6.*\
cos(\[Theta]6).*sin(\[Theta]5).*(cos(\[Theta]5).* ...
  cos(\[Theta]6).*sin(\[Theta]2+\[Theta]3+\[Theta]4)+cos(\[Theta]2+\
\[Theta]3+\[Theta]4).*sin(\[Theta]6))+(-1).*I6.*sin(\[Theta]5).* ...
  sin(\[Theta]6).*(cos(\[Theta]2+\[Theta]3+\[Theta]4).*cos(\[Theta]6)+\
(-1).*cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).* ...
  sin(\[Theta]6))+m6.*(cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.*\
sin(\[Theta]4)+(-1).*l2.* ...
  sin(\[Theta]3+\[Theta]4))+(-1).*(l3.*cos(\[Theta]4)+l2.*cos(\[Theta]\
3+\[Theta]4)+l6.*sin(\[Theta]5)).*sin( ...
  \[Theta]6)).*(sin(\[Theta]2).*((-1).*cos(\[Theta]6).*((l6+l4.*cos(\
\[Theta]5)).*sin(\[Theta]3+\[Theta]4)+( ...
  l5.*cos(\[Theta]3+\[Theta]4)+l3.*sin(\[Theta]3)).*sin(\[Theta]5))+(-\
1).*cos(\[Theta]3+\[Theta]4).*(l4+l6.* ...
  cos(\[Theta]5)).*sin(\[Theta]6))+cos(\[Theta]2).*(cos(\[Theta]3+\
\[Theta]4).*(l6+l4.*cos(\[Theta]5)).*cos(\[Theta]6) ...
  +cos(\[Theta]6).*(l2+l3.*cos(\[Theta]3)+(-1).*l5.*sin(\[Theta]3+\
\[Theta]4)).*sin(\[Theta]5)+(-1).*( ...
  l4+l6.*cos(\[Theta]5)).*sin(\[Theta]3+\[Theta]4).*sin(\[Theta]6)))+\
m6.*((-1).*cos(\[Theta]6).*(l3.* ...
  cos(\[Theta]4)+l2.*cos(\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5))+cos(\
\[Theta]5).*((-1).*l5+l3.*sin(\[Theta]4) ...
  +l2.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]6)).*((-1).*cos(\[Theta]\
3).*(l4+l6.*cos(\[Theta]5)).*cos( ...
  \[Theta]6).*sin(\[Theta]2+\[Theta]4)+((l6+l4.*cos(\[Theta]5)).*sin(\
\[Theta]3).*sin(\[Theta]2+\[Theta]4)+((-1).*cos( ...
  \[Theta]2).*(l2+l3.*cos(\[Theta]3))+l3.*sin(\[Theta]2).*sin(\[Theta]\
3)+l5.*cos(\[Theta]3).*sin(\[Theta]2+\[Theta]4) ...
  ).*sin(\[Theta]5)).*sin(\[Theta]6)+(-1).*cos(\[Theta]2+\[Theta]4).*(\
(l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6) ...
  .*sin(\[Theta]3)+(cos(\[Theta]3).*(l6+l4.*cos(\[Theta]5))+(-1).*l5.*\
sin(\[Theta]3).*sin(\[Theta]5)).* ...
  sin(\[Theta]6)));(-1).*I6.*cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+\
\[Theta]4).*sin(\[Theta]5)+m6.*((-1).*l5+ ...
  l3.*sin(\[Theta]4)).*sin(\[Theta]5).*(cos(\[Theta]5).*(l2.*cos(\
\[Theta]2)+l3.*cos(\[Theta]2+\[Theta]3)+(-1) ...
  .*l5.*sin(\[Theta]2+\[Theta]3+\[Theta]4))+(-1).*l4.*cos(\[Theta]2+\
\[Theta]3+\[Theta]4).*sin(\[Theta]5))+I6.*cos(\[Theta]6) ...
  .*sin(\[Theta]5).*(cos(\[Theta]5).*cos(\[Theta]6).*sin(\[Theta]2+\
\[Theta]3+\[Theta]4)+cos(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]\
6) ...
  )+(-1).*I6.*sin(\[Theta]5).*sin(\[Theta]6).*(cos(\[Theta]2+\[Theta]\
3+\[Theta]4).*cos(\[Theta]6)+(-1).*cos( ...
  \[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]6))+m6.*\
(cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.* ...
  sin(\[Theta]4))+(-1).*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5)).*sin(\
\[Theta]6)).*(sin(\[Theta]2).*(( ...
  -1).*cos(\[Theta]6).*((l6+l4.*cos(\[Theta]5)).*sin(\[Theta]3+\
\[Theta]4)+(l5.*cos(\[Theta]3+\[Theta]4)+l3.* ...
  sin(\[Theta]3)).*sin(\[Theta]5))+(-1).*cos(\[Theta]3+\[Theta]4).*(\
l4+l6.*cos(\[Theta]5)).*sin(\[Theta]6))+ ...
  cos(\[Theta]2).*(cos(\[Theta]3+\[Theta]4).*(l6+l4.*cos(\[Theta]5)).*\
cos(\[Theta]6)+cos(\[Theta]6).*(l2+l3.* ...
  cos(\[Theta]3)+(-1).*l5.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]5)+(\
-1).*(l4+l6.*cos(\[Theta]5)).* ...
  sin(\[Theta]3+\[Theta]4).*sin(\[Theta]6)))+m6.*((-1).*cos(\[Theta]6)\
.*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5) ...
  )+cos(\[Theta]5).*((-1).*l5+l3.*sin(\[Theta]4)).*sin(\[Theta]6)).*((\
-1).*cos(\[Theta]3).*(l4+ ...
  l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]2+\[Theta]4)+((l6+\
l4.*cos(\[Theta]5)).*sin(\[Theta]3).*sin( ...
  \[Theta]2+\[Theta]4)+((-1).*cos(\[Theta]2).*(l2+l3.*cos(\[Theta]3))+\
l3.*sin(\[Theta]2).*sin(\[Theta]3)+l5.* ...
  cos(\[Theta]3).*sin(\[Theta]2+\[Theta]4)).*sin(\[Theta]5)).*sin(\
\[Theta]6)+(-1).*cos(\[Theta]2+\[Theta]4).*((l4+ ...
  l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]3)+(cos(\[Theta]3).\
*(l6+l4.*cos(\[Theta]5))+(-1).* ...
  l5.*sin(\[Theta]3).*sin(\[Theta]5)).*sin(\[Theta]6)));(-1).*I6.*cos(\
\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4) ...
  .*sin(\[Theta]5)+(-1).*l5.*m6.*sin(\[Theta]5).*(cos(\[Theta]5).*(l2.\
*cos(\[Theta]2)+l3.*cos( ...
  \[Theta]2+\[Theta]3)+(-1).*l5.*sin(\[Theta]2+\[Theta]3+\[Theta]4))+(\
-1).*l4.*cos(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]5))+ ...
  I6.*cos(\[Theta]6).*sin(\[Theta]5).*(cos(\[Theta]5).*cos(\[Theta]6).\
*sin(\[Theta]2+\[Theta]3+\[Theta]4)+cos(\[Theta]2+\[Theta]3+ ...
  \[Theta]4).*sin(\[Theta]6))+(-1).*I6.*sin(\[Theta]5).*sin(\[Theta]6)\
.*(cos(\[Theta]2+\[Theta]3+\[Theta]4).*cos(\[Theta]6)+ ...
  (-1).*cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\
\[Theta]6))+m6.*(l5.*cos(\[Theta]5).*cos(\[Theta]6)+( ...
  -1).*l6.*sin(\[Theta]5).*sin(\[Theta]6)).*(sin(\[Theta]2).*((-1).*\
cos(\[Theta]6).*((l6+l4.* ...
  cos(\[Theta]5)).*sin(\[Theta]3+\[Theta]4)+(l5.*cos(\[Theta]3+\
\[Theta]4)+l3.*sin(\[Theta]3)).*sin(\[Theta]5))+(-1).* ...
  cos(\[Theta]3+\[Theta]4).*(l4+l6.*cos(\[Theta]5)).*sin(\[Theta]6))+\
cos(\[Theta]2).*(cos(\[Theta]3+\[Theta]4).*(l6+ ...
  l4.*cos(\[Theta]5)).*cos(\[Theta]6)+cos(\[Theta]6).*(l2+l3.*cos(\
\[Theta]3)+(-1).*l5.*sin(\[Theta]3+ ...
  \[Theta]4)).*sin(\[Theta]5)+(-1).*(l4+l6.*cos(\[Theta]5)).*sin(\
\[Theta]3+\[Theta]4).*sin(\[Theta]6)))+m6.*(( ...
  -1).*l6.*cos(\[Theta]6).*sin(\[Theta]5)+(-1).*l5.*cos(\[Theta]5).*\
sin(\[Theta]6)).*((-1).*cos( ...
  \[Theta]3).*(l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]2+\
\[Theta]4)+((l6+l4.*cos(\[Theta]5)).*sin( ...
  \[Theta]3).*sin(\[Theta]2+\[Theta]4)+((-1).*cos(\[Theta]2).*(l2+l3.*\
cos(\[Theta]3))+l3.*sin(\[Theta]2).*sin( ...
  \[Theta]3)+l5.*cos(\[Theta]3).*sin(\[Theta]2+\[Theta]4)).*sin(\
\[Theta]5)).*sin(\[Theta]6)+(-1).*cos(\[Theta]2+\[Theta]4).* ...
  ((l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]3)+(cos(\
\[Theta]3).*(l6+l4.*cos(\[Theta]5))+( ...
  -1).*l5.*sin(\[Theta]3).*sin(\[Theta]5)).*sin(\[Theta]6)));(-1).*I6.\
*sin(\[Theta]6).*(cos(\[Theta]5) ...
  .*cos(\[Theta]6).*sin(\[Theta]2+\[Theta]3+\[Theta]4)+cos(\[Theta]2+\
\[Theta]3+\[Theta]4).*sin(\[Theta]6))+(-1).*I6.*cos(\[Theta]6) ...
  .*(cos(\[Theta]2+\[Theta]3+\[Theta]4).*cos(\[Theta]6)+(-1).*cos(\
\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]6))+( ...
\

  -1).*l6.*m6.*cos(\[Theta]6).*(sin(\[Theta]2).*((-1).*cos(\[Theta]6).\
*((l6+l4.*cos(\[Theta]5)) ...
  .*sin(\[Theta]3+\[Theta]4)+(l5.*cos(\[Theta]3+\[Theta]4)+l3.*sin(\
\[Theta]3)).*sin(\[Theta]5))+(-1).*cos(\[Theta]3+ ...
  \[Theta]4).*(l4+l6.*cos(\[Theta]5)).*sin(\[Theta]6))+cos(\[Theta]2).\
*(cos(\[Theta]3+\[Theta]4).*(l6+l4.*cos( ...
  \[Theta]5)).*cos(\[Theta]6)+cos(\[Theta]6).*(l2+l3.*cos(\[Theta]3)+(\
-1).*l5.*sin(\[Theta]3+\[Theta]4)).*sin( ...
  \[Theta]5)+(-1).*(l4+l6.*cos(\[Theta]5)).*sin(\[Theta]3+\[Theta]4).*\
sin(\[Theta]6)))+l6.*m6.*sin(\[Theta]6) ...
  .*((-1).*cos(\[Theta]3).*(l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6).*\
sin(\[Theta]2+\[Theta]4)+((l6+l4.* ...
  cos(\[Theta]5)).*sin(\[Theta]3).*sin(\[Theta]2+\[Theta]4)+((-1).*\
cos(\[Theta]2).*(l2+l3.*cos(\[Theta]3))+ ...
  l3.*sin(\[Theta]2).*sin(\[Theta]3)+l5.*cos(\[Theta]3).*sin(\[Theta]\
2+\[Theta]4)).*sin(\[Theta]5)).*sin(\[Theta]6)+( ...
  -1).*cos(\[Theta]2+\[Theta]4).*((l4+l6.*cos(\[Theta]5)).*cos(\
\[Theta]6).*sin(\[Theta]3)+(cos(\[Theta]3).*( ...
  l6+l4.*cos(\[Theta]5))+(-1).*l5.*sin(\[Theta]3).*sin(\[Theta]5)).*\
sin(\[Theta]6)));(-1).*I6.* ...
  sin(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]5)],[(-1).*I6.*cos(\
\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]5) ...
  +m6.*((-1).*l5+l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)).*\
sin(\[Theta]5).*(cos(\[Theta]5).*( ...
  l2.*cos(\[Theta]2)+l3.*cos(\[Theta]2+\[Theta]3)+(-1).*l5.*sin(\
\[Theta]2+\[Theta]3+\[Theta]4))+(-1).*l4.*cos( ...
  \[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]5))+I6.*cos(\[Theta]6).*\
sin(\[Theta]5).*(cos(\[Theta]5).*cos(\[Theta]6).*sin( ...
  \[Theta]2+\[Theta]3+\[Theta]4)+cos(\[Theta]2+\[Theta]3+\[Theta]4).*\
sin(\[Theta]6))+(-1).*I6.*sin(\[Theta]5).*sin(\[Theta]6).*( ...
  cos(\[Theta]2+\[Theta]3+\[Theta]4).*cos(\[Theta]6)+(-1).*cos(\
\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]6))+m6.* ...
\

  (cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.*sin(\[Theta]4)+(-1).*\
l2.*sin(\[Theta]3+\[Theta]4))+( ...
  -1).*(l3.*cos(\[Theta]4)+l2.*cos(\[Theta]3+\[Theta]4)+l6.*sin(\
\[Theta]5)).*sin(\[Theta]6)).*(sin(\[Theta]2) ...
  .*((-1).*cos(\[Theta]6).*((l6+l4.*cos(\[Theta]5)).*sin(\[Theta]3+\
\[Theta]4)+(l5.*cos(\[Theta]3+\[Theta]4)+ ...
  l3.*sin(\[Theta]3)).*sin(\[Theta]5))+(-1).*cos(\[Theta]3+\[Theta]4).\
*(l4+l6.*cos(\[Theta]5)).*sin(\[Theta]6) ...
  )+cos(\[Theta]2).*(cos(\[Theta]3+\[Theta]4).*(l6+l4.*cos(\[Theta]5))\
.*cos(\[Theta]6)+cos(\[Theta]6).*(l2+ ...
  l3.*cos(\[Theta]3)+(-1).*l5.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]\
5)+(-1).*(l4+l6.*cos(\[Theta]5)) ...
  .*sin(\[Theta]3+\[Theta]4).*sin(\[Theta]6)))+m6.*((-1).*cos(\[Theta]\
6).*(l3.*cos(\[Theta]4)+l2.*cos( ...
  \[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5))+cos(\[Theta]5).*((-1).*l5+\
l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)) ...
  .*sin(\[Theta]6)).*((-1).*cos(\[Theta]3).*(l4+l6.*cos(\[Theta]5)).*\
cos(\[Theta]6).*sin(\[Theta]2+\[Theta]4)+ ...
  ((l6+l4.*cos(\[Theta]5)).*sin(\[Theta]3).*sin(\[Theta]2+\[Theta]4)+(\
(-1).*cos(\[Theta]2).*(l2+l3.* ...
  cos(\[Theta]3))+l3.*sin(\[Theta]2).*sin(\[Theta]3)+l5.*cos(\[Theta]\
3).*sin(\[Theta]2+\[Theta]4)).*sin(\[Theta]5)).* ...
  sin(\[Theta]6)+(-1).*cos(\[Theta]2+\[Theta]4).*((l4+l6.*cos(\[Theta]\
5)).*cos(\[Theta]6).*sin(\[Theta]3)+( ...
  cos(\[Theta]3).*(l6+l4.*cos(\[Theta]5))+(-1).*l5.*sin(\[Theta]3).*\
sin(\[Theta]5)).*sin(\[Theta]6))); ...
  I6.*cos(\[Theta]5).^2+I6.*cos(\[Theta]6).^2.*sin(\[Theta]5).^2+m6.*(\
(-1).*l5+l3.*sin( ...
  \[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)).^2.*sin(\[Theta]5).^2+I6.*\
sin(\[Theta]5).^2.*sin(\[Theta]6).^2+m6.* ...
  ((-1).*cos(\[Theta]6).*(l3.*cos(\[Theta]4)+l2.*cos(\[Theta]3+\
\[Theta]4)+l6.*sin(\[Theta]5))+cos(\[Theta]5).* ...
  ((-1).*l5+l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)).*sin(\
\[Theta]6)).^2+m6.*(cos(\[Theta]5).* ...
  cos(\[Theta]6).*(l5+(-1).*l3.*sin(\[Theta]4)+(-1).*l2.*sin(\[Theta]\
3+\[Theta]4))+(-1).*(l3.* ...
  cos(\[Theta]4)+l2.*cos(\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5)).*\
sin(\[Theta]6)).^2;I6.*cos(\[Theta]5).^2+ ...
  I6.*cos(\[Theta]6).^2.*sin(\[Theta]5).^2+m6.*((-1).*l5+l3.*sin(\
\[Theta]4)).*((-1).*l5+ ...
  l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]5).^2+\
I6.*sin(\[Theta]5).^2.*sin(\[Theta]6) ...
  .^2+m6.*((-1).*cos(\[Theta]6).*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]\
5))+cos(\[Theta]5).*((-1).* ...
  l5+l3.*sin(\[Theta]4)).*sin(\[Theta]6)).*((-1).*cos(\[Theta]6).*(l3.\
*cos(\[Theta]4)+l2.*cos( ...
  \[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5))+cos(\[Theta]5).*((-1).*l5+\
l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)) ...
  .*sin(\[Theta]6))+m6.*(cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.\
*sin(\[Theta]4))+(-1).*( ...
  l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5)).*sin(\[Theta]6)).*(cos(\
\[Theta]5).*cos(\[Theta]6).*(l5+(-1).* ...
  l3.*sin(\[Theta]4)+(-1).*l2.*sin(\[Theta]3+\[Theta]4))+(-1).*(l3.*\
cos(\[Theta]4)+l2.*cos(\[Theta]3+ ...
  \[Theta]4)+l6.*sin(\[Theta]5)).*sin(\[Theta]6));I6.*cos(\[Theta]5).^\
2+I6.*cos(\[Theta]6).^2.*sin(\[Theta]5) ...
  .^2+(-1).*l5.*m6.*((-1).*l5+l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\
\[Theta]4)).*sin(\[Theta]5) ...
  .^2+I6.*sin(\[Theta]5).^2.*sin(\[Theta]6).^2+m6.*((-1).*l6.*cos(\
\[Theta]6).*sin(\[Theta]5)+( ...
  -1).*l5.*cos(\[Theta]5).*sin(\[Theta]6)).*((-1).*cos(\[Theta]6).*(\
l3.*cos(\[Theta]4)+l2.*cos( ...
  \[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5))+cos(\[Theta]5).*((-1).*l5+\
l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)) ...
  .*sin(\[Theta]6))+m6.*(l5.*cos(\[Theta]5).*cos(\[Theta]6)+(-1).*l6.*\
sin(\[Theta]5).*sin(\[Theta]6)).* ...
  (cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.*sin(\[Theta]4)+(-1).*\
l2.*sin(\[Theta]3+\[Theta]4))+( ...
  -1).*(l3.*cos(\[Theta]4)+l2.*cos(\[Theta]3+\[Theta]4)+l6.*sin(\
\[Theta]5)).*sin(\[Theta]6));l6.*m6.* ...
  sin(\[Theta]6).*((-1).*cos(\[Theta]6).*(l3.*cos(\[Theta]4)+l2.*cos(\
\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5))+ ...
  cos(\[Theta]5).*((-1).*l5+l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\
\[Theta]4)).*sin(\[Theta]6))+(-1).* ...
  l6.*m6.*cos(\[Theta]6).*(cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*\
l3.*sin(\[Theta]4)+(-1).* ...
  l2.*sin(\[Theta]3+\[Theta]4))+(-1).*(l3.*cos(\[Theta]4)+l2.*cos(\
\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5)).* ...
  sin(\[Theta]6));I6.*cos(\[Theta]5)],[(-1).*I6.*cos(\[Theta]5).*sin(\
\[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]5)+ ...
  m6.*((-1).*l5+l3.*sin(\[Theta]4)).*sin(\[Theta]5).*(cos(\[Theta]5).*\
(l2.*cos(\[Theta]2)+l3.* ...
  cos(\[Theta]2+\[Theta]3)+(-1).*l5.*sin(\[Theta]2+\[Theta]3+\[Theta]\
4))+(-1).*l4.*cos(\[Theta]2+\[Theta]3+\[Theta]4).*sin( ...
  \[Theta]5))+I6.*cos(\[Theta]6).*sin(\[Theta]5).*(cos(\[Theta]5).*\
cos(\[Theta]6).*sin(\[Theta]2+\[Theta]3+\[Theta]4)+cos( ...
  \[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]6))+(-1).*I6.*sin(\
\[Theta]5).*sin(\[Theta]6).*(cos(\[Theta]2+\[Theta]3+\[Theta]4).* ...
\

  cos(\[Theta]6)+(-1).*cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+\
\[Theta]4).*sin(\[Theta]6))+m6.*(cos(\[Theta]5).*cos( ...
  \[Theta]6).*(l5+(-1).*l3.*sin(\[Theta]4))+(-1).*(l3.*cos(\[Theta]4)+\
l6.*sin(\[Theta]5)).*sin( ...
  \[Theta]6)).*(sin(\[Theta]2).*((-1).*cos(\[Theta]6).*((l6+l4.*cos(\
\[Theta]5)).*sin(\[Theta]3+\[Theta]4)+( ...
  l5.*cos(\[Theta]3+\[Theta]4)+l3.*sin(\[Theta]3)).*sin(\[Theta]5))+(-\
1).*cos(\[Theta]3+\[Theta]4).*(l4+l6.* ...
  cos(\[Theta]5)).*sin(\[Theta]6))+cos(\[Theta]2).*(cos(\[Theta]3+\
\[Theta]4).*(l6+l4.*cos(\[Theta]5)).*cos(\[Theta]6) ...
  +cos(\[Theta]6).*(l2+l3.*cos(\[Theta]3)+(-1).*l5.*sin(\[Theta]3+\
\[Theta]4)).*sin(\[Theta]5)+(-1).*( ...
  l4+l6.*cos(\[Theta]5)).*sin(\[Theta]3+\[Theta]4).*sin(\[Theta]6)))+\
m6.*((-1).*cos(\[Theta]6).*(l3.* ...
  cos(\[Theta]4)+l6.*sin(\[Theta]5))+cos(\[Theta]5).*((-1).*l5+l3.*\
sin(\[Theta]4)).*sin(\[Theta]6)).*(( ...
  -1).*cos(\[Theta]3).*(l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\
\[Theta]2+\[Theta]4)+((l6+l4.*cos( ...
  \[Theta]5)).*sin(\[Theta]3).*sin(\[Theta]2+\[Theta]4)+((-1).*cos(\
\[Theta]2).*(l2+l3.*cos(\[Theta]3))+l3.* ...
  sin(\[Theta]2).*sin(\[Theta]3)+l5.*cos(\[Theta]3).*sin(\[Theta]2+\
\[Theta]4)).*sin(\[Theta]5)).*sin(\[Theta]6)+(-1) ...
  .*cos(\[Theta]2+\[Theta]4).*((l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6)\
.*sin(\[Theta]3)+(cos(\[Theta]3).*(l6+ ...
  l4.*cos(\[Theta]5))+(-1).*l5.*sin(\[Theta]3).*sin(\[Theta]5)).*sin(\
\[Theta]6)));I6.*cos(\[Theta]5) ...
  .^2+I6.*cos(\[Theta]6).^2.*sin(\[Theta]5).^2+m6.*((-1).*l5+l3.*sin(\
\[Theta]4)).*((-1).* ...
  l5+l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]5).\
^2+I6.*sin(\[Theta]5).^2.*sin(\[Theta]6) ...
  .^2+m6.*((-1).*cos(\[Theta]6).*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]\
5))+cos(\[Theta]5).*((-1).* ...
  l5+l3.*sin(\[Theta]4)).*sin(\[Theta]6)).*((-1).*cos(\[Theta]6).*(l3.\
*cos(\[Theta]4)+l2.*cos( ...
  \[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5))+cos(\[Theta]5).*((-1).*l5+\
l3.*sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)) ...
  .*sin(\[Theta]6))+m6.*(cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.\
*sin(\[Theta]4))+(-1).*( ...
  l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5)).*sin(\[Theta]6)).*(cos(\
\[Theta]5).*cos(\[Theta]6).*(l5+(-1).* ...
  l3.*sin(\[Theta]4)+(-1).*l2.*sin(\[Theta]3+\[Theta]4))+(-1).*(l3.*\
cos(\[Theta]4)+l2.*cos(\[Theta]3+ ...
  \[Theta]4)+l6.*sin(\[Theta]5)).*sin(\[Theta]6));I6.*cos(\[Theta]5).^\
2+I6.*cos(\[Theta]6).^2.*sin(\[Theta]5) ...
  .^2+m6.*((-1).*l5+l3.*sin(\[Theta]4)).^2.*sin(\[Theta]5).^2+I6.*sin(\
\[Theta]5).^2.*sin( ...
  \[Theta]6).^2+m6.*((-1).*cos(\[Theta]6).*(l3.*cos(\[Theta]4)+l6.*\
sin(\[Theta]5))+cos(\[Theta]5).*(( ...
  -1).*l5+l3.*sin(\[Theta]4)).*sin(\[Theta]6)).^2+m6.*(cos(\[Theta]5).\
*cos(\[Theta]6).*(l5+(-1) ...
  .*l3.*sin(\[Theta]4))+(-1).*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5)).\
*sin(\[Theta]6)).^2;I6.* ...
  cos(\[Theta]5).^2+I6.*cos(\[Theta]6).^2.*sin(\[Theta]5).^2+(-1).*l5.\
*m6.*((-1).*l5+l3.* ...
  sin(\[Theta]4)).*sin(\[Theta]5).^2+I6.*sin(\[Theta]5).^2.*sin(\
\[Theta]6).^2+m6.*((-1).*l6.* ...
  cos(\[Theta]6).*sin(\[Theta]5)+(-1).*l5.*cos(\[Theta]5).*sin(\
\[Theta]6)).*((-1).*cos(\[Theta]6).*( ...
  l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5))+cos(\[Theta]5).*((-1).*l5+l3.\
*sin(\[Theta]4)).*sin(\[Theta]6)) ...
  +m6.*(l5.*cos(\[Theta]5).*cos(\[Theta]6)+(-1).*l6.*sin(\[Theta]5).*\
sin(\[Theta]6)).*(cos(\[Theta]5).* ...
  cos(\[Theta]6).*(l5+(-1).*l3.*sin(\[Theta]4))+(-1).*(l3.*cos(\
\[Theta]4)+l6.*sin(\[Theta]5)).* ...
  sin(\[Theta]6));l6.*m6.*sin(\[Theta]6).*((-1).*cos(\[Theta]6).*(l3.*\
cos(\[Theta]4)+l6.*sin(\[Theta]5) ...
  )+cos(\[Theta]5).*((-1).*l5+l3.*sin(\[Theta]4)).*sin(\[Theta]6))+(-\
1).*l6.*m6.*cos(\[Theta]6) ...
  .*(cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.*sin(\[Theta]4))+(-\
1).*(l3.*cos(\[Theta]4)+ ...
  l6.*sin(\[Theta]5)).*sin(\[Theta]6));I6.*cos(\[Theta]5)],[(-1).*I6.*\
cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+ ...
  \[Theta]4).*sin(\[Theta]5)+(-1).*l5.*m6.*sin(\[Theta]5).*(cos(\
\[Theta]5).*(l2.*cos(\[Theta]2)+l3.* ...
  cos(\[Theta]2+\[Theta]3)+(-1).*l5.*sin(\[Theta]2+\[Theta]3+\[Theta]\
4))+(-1).*l4.*cos(\[Theta]2+\[Theta]3+\[Theta]4).*sin( ...
  \[Theta]5))+I6.*cos(\[Theta]6).*sin(\[Theta]5).*(cos(\[Theta]5).*\
cos(\[Theta]6).*sin(\[Theta]2+\[Theta]3+\[Theta]4)+cos( ...
  \[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]6))+(-1).*I6.*sin(\
\[Theta]5).*sin(\[Theta]6).*(cos(\[Theta]2+\[Theta]3+\[Theta]4).* ...
\

  cos(\[Theta]6)+(-1).*cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+\
\[Theta]4).*sin(\[Theta]6))+m6.*(l5.*cos(\[Theta]5).* ...
  cos(\[Theta]6)+(-1).*l6.*sin(\[Theta]5).*sin(\[Theta]6)).*(sin(\
\[Theta]2).*((-1).*cos(\[Theta]6).*(( ...
  l6+l4.*cos(\[Theta]5)).*sin(\[Theta]3+\[Theta]4)+(l5.*cos(\[Theta]3+\
\[Theta]4)+l3.*sin(\[Theta]3)).*sin(\[Theta]5)) ...
  +(-1).*cos(\[Theta]3+\[Theta]4).*(l4+l6.*cos(\[Theta]5)).*sin(\
\[Theta]6))+cos(\[Theta]2).*(cos(\[Theta]3+\[Theta]4) ...
  .*(l6+l4.*cos(\[Theta]5)).*cos(\[Theta]6)+cos(\[Theta]6).*(l2+l3.*\
cos(\[Theta]3)+(-1).*l5.* ...
  sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]5)+(-1).*(l4+l6.*cos(\[Theta]\
5)).*sin(\[Theta]3+\[Theta]4).*sin(\[Theta]6))) ...
  +m6.*((-1).*l6.*cos(\[Theta]6).*sin(\[Theta]5)+(-1).*l5.*cos(\
\[Theta]5).*sin(\[Theta]6)).*(( ...
  -1).*cos(\[Theta]3).*(l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6).*sin(\
\[Theta]2+\[Theta]4)+((l6+l4.*cos( ...
  \[Theta]5)).*sin(\[Theta]3).*sin(\[Theta]2+\[Theta]4)+((-1).*cos(\
\[Theta]2).*(l2+l3.*cos(\[Theta]3))+l3.* ...
  sin(\[Theta]2).*sin(\[Theta]3)+l5.*cos(\[Theta]3).*sin(\[Theta]2+\
\[Theta]4)).*sin(\[Theta]5)).*sin(\[Theta]6)+(-1) ...
  .*cos(\[Theta]2+\[Theta]4).*((l4+l6.*cos(\[Theta]5)).*cos(\[Theta]6)\
.*sin(\[Theta]3)+(cos(\[Theta]3).*(l6+ ...
  l4.*cos(\[Theta]5))+(-1).*l5.*sin(\[Theta]3).*sin(\[Theta]5)).*sin(\
\[Theta]6)));I6.*cos(\[Theta]5) ...
  .^2+I6.*cos(\[Theta]6).^2.*sin(\[Theta]5).^2+(-1).*l5.*m6.*((-1).*\
l5+l3.*sin(\[Theta]4) ...
  +l2.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]5).^2+I6.*sin(\[Theta]5)\
.^2.*sin(\[Theta]6).^2+m6.*((-1) ...
  .*l6.*cos(\[Theta]6).*sin(\[Theta]5)+(-1).*l5.*cos(\[Theta]5).*sin(\
\[Theta]6)).*((-1).*cos(\[Theta]6) ...
  .*(l3.*cos(\[Theta]4)+l2.*cos(\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]\
5))+cos(\[Theta]5).*((-1).*l5+l3.* ...
  sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]6))+m6.*(\
l5.*cos(\[Theta]5).*cos(\[Theta]6)+(-1).* ...
  l6.*sin(\[Theta]5).*sin(\[Theta]6)).*(cos(\[Theta]5).*cos(\[Theta]6)\
.*(l5+(-1).*l3.*sin(\[Theta]4)+( ...
  -1).*l2.*sin(\[Theta]3+\[Theta]4))+(-1).*(l3.*cos(\[Theta]4)+l2.*\
cos(\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5) ...
  ).*sin(\[Theta]6));I6.*cos(\[Theta]5).^2+I6.*cos(\[Theta]6).^2.*sin(\
\[Theta]5).^2+(-1).*l5.* ...
  m6.*((-1).*l5+l3.*sin(\[Theta]4)).*sin(\[Theta]5).^2+I6.*sin(\
\[Theta]5).^2.*sin(\[Theta]6).^2+ ...
  m6.*((-1).*l6.*cos(\[Theta]6).*sin(\[Theta]5)+(-1).*l5.*cos(\[Theta]\
5).*sin(\[Theta]6)).*((-1) ...
  .*cos(\[Theta]6).*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5))+cos(\
\[Theta]5).*((-1).*l5+l3.*sin( ...
  \[Theta]4)).*sin(\[Theta]6))+m6.*(l5.*cos(\[Theta]5).*cos(\[Theta]6)\
+(-1).*l6.*sin(\[Theta]5).*sin( ...
  \[Theta]6)).*(cos(\[Theta]5).*cos(\[Theta]6).*(l5+(-1).*l3.*sin(\
\[Theta]4))+(-1).*(l3.*cos(\[Theta]4) ...
  +l6.*sin(\[Theta]5)).*sin(\[Theta]6));I6.*cos(\[Theta]5).^2+l5.^2.*\
m6.*sin(\[Theta]5).^2+I6.* ...
  cos(\[Theta]6).^2.*sin(\[Theta]5).^2+I6.*sin(\[Theta]5).^2.*sin(\
\[Theta]6).^2+m6.*((-1).*l6.* ...
  cos(\[Theta]6).*sin(\[Theta]5)+(-1).*l5.*cos(\[Theta]5).*sin(\
\[Theta]6)).^2+m6.*(l5.*cos(\[Theta]5).* ...
  cos(\[Theta]6)+(-1).*l6.*sin(\[Theta]5).*sin(\[Theta]6)).^2;l6.*m6.*\
sin(\[Theta]6).*((-1).* ...
  l6.*cos(\[Theta]6).*sin(\[Theta]5)+(-1).*l5.*cos(\[Theta]5).*sin(\
\[Theta]6))+(-1).*l6.*m6.* ...
  cos(\[Theta]6).*(l5.*cos(\[Theta]5).*cos(\[Theta]6)+(-1).*l6.*sin(\
\[Theta]5).*sin(\[Theta]6));I6.* ...
  cos(\[Theta]5)],[(-1).*I6.*sin(\[Theta]6).*(cos(\[Theta]5).*cos(\
\[Theta]6).*sin(\[Theta]2+\[Theta]3+\[Theta]4)+cos( ...
  \[Theta]2+\[Theta]3+\[Theta]4).*sin(\[Theta]6))+(-1).*I6.*cos(\
\[Theta]6).*(cos(\[Theta]2+\[Theta]3+\[Theta]4).*cos(\[Theta]6)+( ...
\

  -1).*cos(\[Theta]5).*sin(\[Theta]2+\[Theta]3+\[Theta]4).*sin(\
\[Theta]6))+(-1).*l6.*m6.*cos(\[Theta]6).*(sin( ...
  \[Theta]2).*((-1).*cos(\[Theta]6).*((l6+l4.*cos(\[Theta]5)).*sin(\
\[Theta]3+\[Theta]4)+(l5.*cos(\[Theta]3+\[Theta]4) ...
  +l3.*sin(\[Theta]3)).*sin(\[Theta]5))+(-1).*cos(\[Theta]3+\[Theta]4)\
.*(l4+l6.*cos(\[Theta]5)).*sin( ...
  \[Theta]6))+cos(\[Theta]2).*(cos(\[Theta]3+\[Theta]4).*(l6+l4.*cos(\
\[Theta]5)).*cos(\[Theta]6)+cos(\[Theta]6).*(l2+ ...
  l3.*cos(\[Theta]3)+(-1).*l5.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]\
5)+(-1).*(l4+l6.*cos(\[Theta]5)) ...
  .*sin(\[Theta]3+\[Theta]4).*sin(\[Theta]6)))+l6.*m6.*sin(\[Theta]6).\
*((-1).*cos(\[Theta]3).*(l4+l6.* ...
  cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]2+\[Theta]4)+((l6+l4.*\
cos(\[Theta]5)).*sin(\[Theta]3).*sin(\[Theta]2+ ...
  \[Theta]4)+((-1).*cos(\[Theta]2).*(l2+l3.*cos(\[Theta]3))+l3.*sin(\
\[Theta]2).*sin(\[Theta]3)+l5.*cos( ...
  \[Theta]3).*sin(\[Theta]2+\[Theta]4)).*sin(\[Theta]5)).*sin(\[Theta]\
6)+(-1).*cos(\[Theta]2+\[Theta]4).*((l4+l6.* ...
  cos(\[Theta]5)).*cos(\[Theta]6).*sin(\[Theta]3)+(cos(\[Theta]3).*(\
l6+l4.*cos(\[Theta]5))+(-1).*l5.* ...
  sin(\[Theta]3).*sin(\[Theta]5)).*sin(\[Theta]6)));l6.*m6.*sin(\
\[Theta]6).*((-1).*cos(\[Theta]6).*( ...
  l3.*cos(\[Theta]4)+l2.*cos(\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5))+\
cos(\[Theta]5).*((-1).*l5+l3.* ...
  sin(\[Theta]4)+l2.*sin(\[Theta]3+\[Theta]4)).*sin(\[Theta]6))+(-1).*\
l6.*m6.*cos(\[Theta]6).*(cos(\[Theta]5) ...
  .*cos(\[Theta]6).*(l5+(-1).*l3.*sin(\[Theta]4)+(-1).*l2.*sin(\
\[Theta]3+\[Theta]4))+(-1).*(l3.* ...
  cos(\[Theta]4)+l2.*cos(\[Theta]3+\[Theta]4)+l6.*sin(\[Theta]5)).*\
sin(\[Theta]6));l6.*m6.*sin(\[Theta]6).*(( ...
  -1).*cos(\[Theta]6).*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]5))+cos(\
\[Theta]5).*((-1).*l5+l3.* ...
  sin(\[Theta]4)).*sin(\[Theta]6))+(-1).*l6.*m6.*cos(\[Theta]6).*(cos(\
\[Theta]5).*cos(\[Theta]6).*(l5+( ...
  -1).*l3.*sin(\[Theta]4))+(-1).*(l3.*cos(\[Theta]4)+l6.*sin(\[Theta]\
5)).*sin(\[Theta]6));l6.* ...
  m6.*sin(\[Theta]6).*((-1).*l6.*cos(\[Theta]6).*sin(\[Theta]5)+(-1).*\
l5.*cos(\[Theta]5).*sin( ...
  \[Theta]6))+(-1).*l6.*m6.*cos(\[Theta]6).*(l5.*cos(\[Theta]5).*cos(\
\[Theta]6)+(-1).*l6.*sin( ...
  \[Theta]5).*sin(\[Theta]6));I6.*cos(\[Theta]6).^2+l6.^2.*m6.*cos(\
\[Theta]6).^2+I6.*sin(\[Theta]6).^2+ ...
  l6.^2.*m6.*sin(\[Theta]6).^2;0],[(-1).*I6.*sin(\[Theta]2+\[Theta]3+\
\[Theta]4).*sin(\[Theta]5);I6.* ...
  cos(\[Theta]5);I6.*cos(\[Theta]5);I6.*cos(\[Theta]5);0;I6]];